func main() {
            defer func() {
                if r := recover(); r != nil {
                    println("Recovered from", r);
                }
            }()
            panic("Something went wrong");
        }